version: "2"

services:
    zookeeper1:
        image: confluentinc/cp-zookeeper:latest
        restart: always
        container_name: zookeeper1
        ports:
            - 2181:2181
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888

    zookeeper2:
        image: confluentinc/cp-zookeeper:latest
        restart: always
        container_name: zookeeper2
        ports:
            - 2182:2182
        environment:
            ZOOKEEPER_CLIENT_PORT: 2182
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SERVER_ID: 2
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888

    zookeeper3:
        image: confluentinc/cp-zookeeper:latest
        restart: always
        container_name: zookeeper3
        ports:
            - 2183:2183
        environment:
            ZOOKEEPER_CLIENT_PORT: 2183
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SERVER_ID: 3
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888

    kafka1:
        image: confluentinc/cp-kafka:latest
        container_name: kafka1
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
            KAFKA_BROKER_ID: 1
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3

    kafka2:
        image: confluentinc/cp-kafka:latest
        container_name: kafka2
        ports:
            - 9093:9093
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://localhost:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
            KAFKA_BROKER_ID: 2
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3

    kafka3:
        image: confluentinc/cp-kafka:latest
        container_name: kafka3
        ports:
            - 9094:9094
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://localhost:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
            KAFKA_BROKER_ID: 3
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
